# Site settings
title: Jacob Lazarchik
description: a website all about me! 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacob Lazarchik
user_description: Lifelong Learner.
user_title: Research Scientist
email: lazarchik.jacob@gmail.com
github_username:  JacobGitz

# Google-analytics
#google-analytics:
  #id: ""

#exclude: ['package.json', 'src' , 'node_modules']
